name: exercise CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Build the Preprocess image
        run: docker build ./preprocess --tag prany/exercise_preprocessing
      - name: Push the Preprocess image
        run: docker push prany/exercise_preprocessing
      - name: Build the Train image
        run: docker build ./train --tag prany/exercise_train
      - name: Push the Train image
        run: docker push prany/exercise_train
      - name: Build the Test image
        run: docker build ./test --tag prany/exercise_test
      - name: Push the Test image
        run: docker push prany/exercise_test
      - name: Build the Deploy image
        run: docker build ./deploy --tag prany/exercise_deploy
      - name: Push the Deploy image
        run: docker push prany/exercise_deploy
