# Use seldon-serve-access in the config folder to provide your AWS credentials.

apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: xgboost
spec:
  name: iris
  predictors:
    - graph:
        children: []
        implementation: XGBOOST_SERVER
        modelUri: s3://mytestbucketexercise
        envSecretRefName: test-key
        name: classifier
      name: default
      replicas: 1
